# Generated by Django 3.2.12 on 2022-03-07 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='therapycenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2255)),
                ('location', models.CharField(max_length=255)),
                ('candidates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientsOfTheclinic', to=settings.AUTH_USER_MODEL)),
                ('therapists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiversofTheclinic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
