# Generated by Django 3.2.12 on 2022-03-07 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mentalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activitylevel', models.SmallIntegerField(choices=[(0, 'Not being even a little bit active'), (3, 'Being a little active '), (5, 'Being avaragely active today'), (10, 'Iam extremely active today')], default=0)),
                ('stresslevel', models.SmallIntegerField(choices=[(0, 'not even a little ounce of stress'), (3, 'just alittle bit of stress'), (5, 'Experiencing avarage amount of stress'), (7, 'Experiencing an above average amount of stress'), (10, 'Experiencing an extremely high amount of stress')], default=0)),
                ('happinesslevel', models.SmallIntegerField(choices=[(0, 'no tinge of happiness'), (3, 'just a little bit of happiness'), (5, 'Avaragely happy'), (7, 'Above avarage in hapiness lavel'), (10, 'Very  very happy ')], default=0)),
                ('dateOflogging', models.DateTimeField(auto_now_add=True)),
                ('candidates_note', models.TextField()),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidatefor_therapy', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_administor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
